PHPVER = 7.2
APP = my-app

zeploy-target-install:
    composer install
    phpunit

zeploy-target-reload:
    cp /etc/zingle/$(APP).conf .env.local
    sudo systemctl restart php$(PHPVER)-fpm

.PHONY: target-install target-reload
